project_alpha/billingapp/urls.py
from django.urls import path
from billingapp.views import (index, ProductCreateView, ProductListView, ProductDetailView, ProductUpdateView, productsjson,
	VendorCreateView, VendorListView, VendorDetailView, VendorUpdateView, VendorDeleteView,
	CustomerCreateView, CustomerListView, CustomerDetailView, CustomerUpdateView, customersjson,
	InventoryListView,
	invoice_create,
	)

app_name = 'billingapp'

urlpatterns = [
	path('',index, name='billing_home'),
	path('product-entry/',ProductCreateView.as_view(), name = 'entry_product'),
	path('product-list/', ProductListView.as_view(), name = 'list_product'),
	path('product-detail/<int:pk>',ProductDetailView.as_view(),name = 'detail_product'),
	path('product-update/<int:pk>',ProductUpdateView.as_view(),name = 'update_product'),
	path('productsjson', productsjson, name='productsjson'),

	path('vendor-list/',VendorListView.as_view(), name = 'list_vendor'),
	path('vendor-entry/',VendorCreateView.as_view(), name = 'entry_vendor'),
	path('vendor-detail/<int:pk>',VendorDetailView.as_view(),name = 'detail_vendor'),
	path('vendor-update/<int:pk>',VendorUpdateView.as_view(),name = 'update_vendor'),
	path('vendor-delete/<int:pk>',VendorDeleteView.as_view(),name = 'delete_vendor'),

	path('customer-entry/',CustomerCreateView.as_view(), name = 'entry_customer'),
	path('customer-list/',CustomerListView.as_view(), name = 'list_customer'),
	path('customer-detail/<int:pk>',CustomerDetailView.as_view(),name = 'detail_customer'),
	path('customer-update/<int:pk>',CustomerUpdateView.as_view(),name = 'update_customer'),
    path('customersjson', customersjson, name='customersjson'),
	
	path('inventory-list/', InventoryListView.as_view(), name = 'list_inventory'),
	
	path('invoices/new', invoice_create, name='create_invoice'),


	
    

	]

project_alpha/project_alpha/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('billingapp/', include('billingapp.urls')),
    path('', views.IndexTemplateView.as_view(), name = 'home')
]

project_alpha/billingapp/forms.py
from django.forms import ModelForm
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from .models import Vendor, Customer, Inventory, Product

class VendorForm(ModelForm):
	class Meta:
       		model =	Vendor
       		fields='__all__'
	        widgets = {
	            'vendor_phone1': PhoneNumberPrefixWidget(initial='IN'),
	            'vendor_phone2': PhoneNumberPrefixWidget(initial='IN'),
            }


class CustomerForm(ModelForm):
	class Meta:
       		model =	Customer
       		fields='__all__'
	        widgets = {
	            'customer_phone': PhoneNumberPrefixWidget(initial='IN'),
	            'customer_phone2': PhoneNumberPrefixWidget(initial='IN'),
            }

class InventoryForm(ModelForm):
	class Meta:
		model = Inventory
		exclude = ['product']


class ProductInventoryForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

project_alpha/billingapp/views.py
import datetime
import json
# import num2words

from django.shortcuts import (render, get_object_or_404, redirect)
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.db.models import Max
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumber

from .utils import (
                    invoice_data_validator,
                    invoice_data_processor,
                    add_customer_book,
                    auto_deduct_book_from_invoice,
                    update_inventory,
                    update_products_from_invoice
                    )

from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from .models import Product, Vendor, Inventory, Invoice, Customer
from .forms import	(VendorForm, CustomerForm, InventoryForm)


# Create your views here.

def index(req):
	return render(req, 'billingapp/billingapp_base.html')


#Product CRUDs

class ProductCreateView(CreateView):
    model = Product
    # template_name = "product_form.html" (By default)
    # form_class = ProductForm
    fields = '__all__'
    success_url = reverse_lazy('billingapp:list_product')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['product_form'] = context['form'] OR
        context['product_form'] = self.get_form()
        context['inventory_form'] = InventoryForm()
        return context

    def form_valid(self, form):
        inventory_form = InventoryForm(self.request.POST)
        if inventory_form.is_valid():
            p = form.save()
            i = inventory_form.save(commit=False)
            i.product = p
            i.save()
        return super().form_valid(form)

    # def form_valid(self, p_form):
    #     inventory_form = InventoryForm()

    #     if inventory_form.is_valid():
    #         p_id = p_form.save()
    #         inv_id = inventory_form.save(commit=False)
    #         inv_id.product = p_id
    #         inv_id.save()

    #     return super().form_valid(p_form)


class ProductListView(ListView):
    model = Product
    # template_name = "product_list.html" (By default)


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product' #default is also same:<model_name>

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_obj = context['product']
        context['vendiz'] = product_obj.vendors.all()
        return context


class ProductUpdateView(UpdateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('billingapp:list_product')
    # forms = [InventoryForm,]
    # template_name = "billingapp/productinventoryupdate_form.html"
     # template_name = "product_form.html" (By default)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['product_form'] = context['form'] OR
        context['product_form'] = self.get_form()
        context['inventory_form'] = InventoryForm(instance=self.object.inventories)
        return context

    def form_valid(self, form):
        x = super().form_valid(form)
        inventory_form = InventoryForm(self.request.POST, instance=self.object.inventories)
        if inventory_form.is_valid():
            inventory_form.save()
        return x

    # def form_valid(self, p_form):
    #     p_id = p_form.save()
    #     inv_id = Inventory.objects.get(product = p_id)
    #     inv_id.inv_available = p_id['inv_available']
    #     inv_id.inv_allocated = p_id['inv_allocated']      
    #     return super().form_valid(p_form)


#Vendor  CRUDs

class VendorCreateView(CreateView):
    model = Vendor
    form_class = VendorForm
    success_url = reverse_lazy('billingapp:list_vendor')
   # template_name = "vendor_form.html" (By default)

class VendorListView(ListView):
    model = Vendor
   # template_name = "vendor_list.html" (By default)


class VendorDetailView(DetailView):
    model = Vendor

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        vendor_obj = context['vendor']
        context['productz'] = vendor_obj.products.all()
        return context


class VendorUpdateView(UpdateView):
    model = Vendor
    fields = '__all__'
    success_url = reverse_lazy('billingapp:list_vendor')


class VendorDeleteView(DeleteView):
    model = Vendor
    success_url = reverse_lazy('billingapp:list_vendor')
    # template_name = "vendor_confirm_delete.html"(Default)


class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('billingapp:list_customer')
   # template_name = "customer_form.html" (By default)


class CustomerListView(ListView):
    model = Customer
   # template_name = "customer_list.html" (By default)


class CustomerDetailView(DetailView):
    model = Customer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer_obj = context['customer']
        context['invoicez'] = customer_obj.invoices.all()
        return context


class CustomerUpdateView(UpdateView):
    model = Customer
    fields = '__all__'
    success_url = reverse_lazy('billingapp:list_customer')

#Inventory CRUD
class InventoryListView(ListView):
    model = Inventory
    #template_name = 'inventory_list.html'(Default)


class InventoryCreateView(CreateView):
    model = Inventory
    fields = '__all__'
    success_url = reverse_lazy('billingapp:list_inventory')
    # template_name = "inventory_form.html" (By default)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['product_form'] = context['form'] OR
        context['inventory_form'] = self.get_form()
        return context




# Invoice, products and customers ===============================================

def invoice_create(request):
    # if business info is blank redirect to update it
   
    # user_profile = get_object_or_404(User, user=request.user)
    # if not user_profile.business_title:
    #     return redirect('user_profile_edit')

    context = {}
    context['default_invoice_number'] = int(Invoice.objects.aggregate(Max('invoice_number'))['invoice_number__max'])
    if not context['default_invoice_number']:
        context['default_invoice_number'] = 1
    else:
        context['default_invoice_number'] += 1

    context['default_invoice_date'] = datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d')

    if request.method == 'POST':
        print("POST received - Invoice Data")

        invoice_data = request.POST

        validation_error = invoice_data_validator(invoice_data)

        if validation_error:
            context["error_message"] = validation_error
            return render(request, 'billingapp/invoice_create.html', context)

        # valid invoice data
        print("Valid Invoice Data")

        invoice_data_processed = invoice_data_processor(invoice_data)
        # save customer
        customer = None

        try:
            customer = Customer.objects.get(
                                            # user=request.user,
                                            customer_name=invoice_data['customer-name'],
                                            customer_address=invoice_data['customer-address'],
                                            customer_phone=invoice_data['customer-phone'],
                                            customer_gst=invoice_data['customer-gst'])
        except:
            print("===============> customer not found")
            print(invoice_data['customer-name'])
            print(invoice_data['customer-address'])
            print(invoice_data['customer-phone'])
            print(invoice_data['customer-gst'])

        if not customer:
            print("CREATING CUSTOMER===============>")
            customer = Customer(
                # user=request.user,
                customer_name=invoice_data['customer-name'],
                customer_address=invoice_data['customer-address'],
                customer_phone=invoice_data['customer-phone'],
                customer_gst=invoice_data['customer-gst'])
            # create customer book
            customer.save()
            add_customer_book(customer)

        # save product
        update_products_from_invoice(invoice_data_processed, 
                                    # request
                                    )


        # save invoice
        invoice_data_processed_json = json.dumps(invoice_data_processed)
        new_invoice = Invoice(
                              # user=request.user,
                              invoice_number=int(invoice_data['invoice-number']),
                              invoice_date=datetime.datetime.strptime(invoice_data['invoice-date'], '%Y-%m-%d'),
                              customer=customer, invoice_json=invoice_data_processed_json)
        new_invoice.save()
        print("INVOICE SAVED")

        # update_inventory(new_invoice, request)
        # print("INVENTORY UPDATED")

        auto_deduct_book_from_invoice(new_invoice)
        print("CUSTOMER BOOK UPDATED")

        return redirect('billingapp/product_list.html')
        # return redirect('invoice_viewer', invoice_id=new_invoice.id)

    return render(request, 'billingapp/invoice_create.html', context)



def invoices(request):
    context = {}
    context['invoices'] = Invoice.objects.filter(user=request.user).order_by('-id')
    return render(request, 'gstbillingapp/invoices.html', context)



# def invoice_viewer(request, invoice_id):
#     invoice_obj = get_object_or_404(Invoice, user=request.user, id=invoice_id)
#     user_profile = get_object_or_404(UserProfile, user=request.user)

#     context = {}
#     context['invoice'] = invoice_obj
#     context['invoice_data'] = json.loads(invoice_obj.invoice_json)

project_alpha/billingapp/templates/billingapp/billingapp_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static "billingapp/main.css" %}">

	<title>WARDROBE</title>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'billingapp:billing_home'%}">Bill Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'admin:index'%}">Admin</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'billingapp:create_invoice'%}">Create Invoice</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="{% url 'billingapp:list_product'%}">Products</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="{% url 'billingapp:list_vendor'%}">Vendors</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="{% url 'billingapp:list_customer'%}">Customers</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Custom</a>
          </li>

         </ul>
      </div>

  </nav>

	<div class="container">

		{% block body_block %}

		WELCOME TO BILLING APP

		{% endblock %}

	</div>
	
  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

  <!-- Custom JS -->
  {% block includejs %}
  {% endblock %}

</body>
</html>

project_alpha/billingapp/templates/billingapp/customer_detail.html
{% extends 'billingapp/billingapp_base.html' %}

{% block body_block %}

	<h3>Customer Detail Page</h3>
	<h1> <b>		{{customer}}		</b></h1>

	<h5><a href="{%url 'billingapp:update_customer' pk=customer.pk %}">Edit</a></h5>

	
<div>
	<h3><u> Customer Invoices :</u></h3>

	<ul>
		{% for x in productz %}
		<li> {{x.product_code}}</li>
		{% endfor %}
	</ul>
</div>

	<p>
		<a href="{% url 'billingapp:list_customer'%}">Click here to Go to Customer List</a>
	</p>

{% endblock %}

project_alpha/billingapp/templates/billingapp/customer_form.html
{% extends 'billingapp/billingapp_base.html' %}

{% block body_block %}

	<h1> Fill Out The Customer Details</h1>
	
	<form method='POST'>
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value='Submit'>
	</form>

{% endblock %}

project_alpha/billingapp/templates/billingapp/customer_list.html
{% extends 'billingapp/billingapp_base.html' %}

{% load static %}

{% block body_block %}

<div class="row">
	<div class="col">
		<h2>Customers</h2>
	</div>
	<div class="col">
		<a href="{% url 'billingapp:entry_customer' %}" id="add_customer_btn"><button type="button" class="btn btn-primary">Add New</button></a>
	</div>
</div>

<table class="table table-bordered">
	<thead>
		<th>S.No</th>			
		<th>Name</th>
		<th colspan="2">Options</th>
	</thead>
	<tbody class="two-col-form">
		{% for x in customer_list %}
		<tr>
			<td>{{forloop.counter}}</td>			
			<td><a href= "{{ x.get_absolute_url }}" >{{x.customer_name}}</a></td>
			<td><a href="{%url 'billingapp:update_customer' pk=x.pk %}"><button type="button" class="btn btn-dark">Edit</button></a></td>
			{# <td><a href="{%url 'billingapp:delete_customer' pk=x.pk %}"><button type="button" class="btn btn-danger">Delete</button></a></td> #}

		</tr>
		{% endfor %}
	</tbody>
</table>


{% endblock %}

project_alpha/billingapp/templates/billingapp/inventory_list.html
{% extends 'billingapp/billingapp_base.html' %}

{% block body_block %}

	<h1> List of All Inventories</h1>

	<table>
		<thead>
			<th>S.No</th>
			<th>Code</th>
			<th>Availble</th>
			<th>Allocated</th>
		</thead>

		
			{% for x in inventory_list %}
			
			<tr>	
				<td> {{ forloop.counter }}</td>	
				<td>{{x.product}}</td>
				<td>{{x.inv_available}}</td>
				<td>{{ x.inv_allocated }}</td>
				
			</tr>
			
			{% endfor %}

	</table>

	<br>
	
	<p>
		<a href="{% url 'billingapp:entry_product'%}">Click here to Add Products</a>
	</p>

{% endblock %}

project_alpha/billingapp/templates/billingapp/invoice_create.html
{% extends 'billingapp/billingapp_base.html' %}


{% load static %}
<!doctype html>

{% block body_block %}

<h2>Create Invoice</h2>

<form method="POST" id="invoice-form">

	<table class="table table-bordered">
		<thead>
			<tr>
				<th class="table-active" scope="col" colspan="4">Invoice Details</th>
			</tr>
		</thead>

		<tbody class="two-col-form">
			<tr>
				<th scope="row">Invoice Number</th>
				<td class="form-input-td"><input name="invoice-number" type="number" class="form-control" placeholder="Invoice Number" value="{{default_invoice_number}}"></td>
				<th scope="row">Date</th>
				<td class="form-input-td"><input name="invoice-date" type="date" class="form-control", value="{{default_invoice_date}}"></td>
			</tr>
		</tbody>
	</table>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th class="table-active" scope="col" colspan="4">Customer Details</th>
			</tr>
		</thead>

		<tbody class="two-col-form">
			<tr>
				<th scope="row">Customer Name</th>
				<td class="form-input-td customer_search_area"><input autocomplete="off" name="customer-name" type="text" class="form-control customer_search_input" id="customer-name-input" list="suggestions"placeholder="Customer Name" required><datalist id="suggestions"></datalist>
				</td>
				<th scope="row">Customer Address</th>
				<td class="form-input-td"><input autocomplete="off" name="customer-address" type="text" class="form-control" id="customer-address-input" placeholder="Customer Address" required></td>
			</tr>
			<tr>
				<th scope="row">Customer Mobile Number</th>
				<td class="form-input-td"><input autocomplete="off" name="customer-phone" type="tel" class="form-control" id="customer-phone-input" placeholder="Customer Mobile Number"></td>
				<th scope="row">Customer GST</th>
				<td class="form-input-td"><input autocomplete="off" name="customer-gst" type="text" class="form-control" id="customer-gst-input" placeholder="Customer GST" maxlength="15" pattern="([A-Za-z0-9]{15})|(^$)"></td>
			</tr>

		</tbody>
	</table>

	<table class="table table-bordered">
		<tbody class="two-col-form">
			<tr>
				<th scope="row">Vehicle Number</th>
				<td class="form-input-td"><input autocomplete="off" name="vehicle-number" type="text" class="form-control" placeholder="Vehicle Number">
				</td>
				<th scope="row"></th>
				<td class="form-input-td">
					<div class="form-check">
						<input class="form-check-input" name="igstcheck" type="checkbox" id="igstcheck">
						<label class="form-check-label" for="igstcheck">
							IGST
						</label>
					</div>
				</td>
			</tr>
		</tbody>
	</table>

	<table class="table table-bordered" id="invoice-form-items-table">
		<thead>
			<th class="table-active" scope="col" colspan="13">Items</th>

			<tr>
				<th scope="col">Sl No.</th>
				<th scope="col">Product</th>
				<th scope="col">HSN / SAC</th>
				<th scope="col">Unit</th>
				<th scope="col">Qty</th>
				<th scope="col">Rate with GST</th>
				<th scope="col">GST %</th>
				<th scope="col">Rate without GST</th>


				<th scope="col">Amt without GST</th>
				<th scope="col">SGST</th>
				<th scope="col">CGST</th>
				<th scope="col">IGST</th>
				<th scope="col">Amt with GST</th>

			</tr>
		</thead>
		<tbody id="invoice-form-items-table-body">
			<tr>
				<td class="invoice-item-slno">1</td>
				<td class="form-input-td"><input name="invoice-product" type="text" class="form-control product_search_area product_search_input" placeholder="Product"></td>
				<td class="form-input-td"><input name="invoice-hsn" type="text" class="form-control" placeholder="HSN"></td>
				<td class="form-input-td"><input name="invoice-unit" type="text" class="form-control" placeholder="Unit"></td>
				<td class="form-input-td"><input name="invoice-qty" type="number" step="any" class="form-control" placeholder="Qty"></td>
				<td class="form-input-td"><input name="invoice-rate-with-gst" type="number" step="any" class="form-control" placeholder="Rate with GST"></td>
				<td class="form-input-td"><input name="invoice-gst-percentage" type="number" step="any" class="form-control" placeholder="GST %"></td>


				<td class="form-input-td"><input name="invoice-rate-without-gst" type="number" step="any" class="form-control" placeholder="Rate without GST" tabindex=-1 readonly></td>
				<td class="form-input-td"><input name="invoice-amt-without-gst" type="number" step="any" class="form-control" tabindex=-1 readonly></td>
				<td class="form-input-td"><input name="invoice-amt-sgst" type="number" step="any" class="form-control" tabindex=-1 readonly></td>
				<td class="form-input-td"><input name="invoice-amt-cgst" type="number" step="any" class="form-control" tabindex=-1 readonly></td>
				<td class="form-input-td"><input name="invoice-amt-igst" type="number" step="any" class="form-control" tabindex=-1 readonly></td>
				<td class="form-input-td"><input name="invoice-amt-with-gst" type="number" step="any" class="form-control" tabindex=-1 readonly></td>
			</tr>
		</tbody>

		<tr>
			<td colspan="8" class="text-right"><strong>TOTAL:</strong></td>
			<td class="form-input-td"><input name="invoice-total-amt-without-gst" type="number" step="any" class="form-control" readonly></td>
			<td class="form-input-td"><input name="invoice-total-amt-sgst" type="number" step="any" class="form-control" readonly></td>
			<td class="form-input-td"><input name="invoice-total-amt-cgst" type="number" step="any" class="form-control" readonly></td>
			<td class="form-input-td"><input name="invoice-total-amt-igst" type="number" step="any" class="form-control" readonly></td>
			<td class="form-input-td"><input name="invoice-total-amt-with-gst" type="number" step="any" class="form-control" readonly></td>
		</tr>

	</table>
	{% csrf_token %}
	<button class="btn btn-primary" id="invoice-form-addrow">+</button>
	<button type="submit" class="btn btn-primary">Submit</button>

</form>


</div>
<div id="customer_search_bar"></div>
<div id="product_search_bar"></div>


{% endblock %}


{% block includejs %}
<script src="{% static "billingapp/main.js" %}"></script>
<script src="{% static "billingapp/fuse-3.4.6.min.js" %}"></script>
{# <script src="https://cdn.jsdelivr.net/npm/fuse.js@7.0.0"></script> #}

{% endblock %}

project_alpha/billingapp/templates/billingapp/product_detail.html
{% extends 'billingapp/billingapp_base.html' %}

{% block body_block %}

	<h1> Detail of The Product:		</h1>
	<h5><a href="{%url 'billingapp:update_product' pk=product.pk %}">Edit</a></h5>
	
			{{product}}
			{{vendiz}}
	

	<h2> List of Vendors for the Product :</h2>

	<ul>
		{% for x in vendiz %}
		<li> {{x.vendor_name}}</li>
		{% endfor %}
	</ul>

	<p>
		<a href="{% url 'billingapp:list_product'%}">Click here to Go to Product List</a>
	</p>

{% endblock %}

project_alpha/billingapp/templates/billingapp/product_list.html
{% extends 'billingapp/billingapp_base.html' %}

{% block body_block %}

	<h1> List of All Products</h1>

	<table>
		<thead>
			<th>S.No</th>
			<th>Code</th>
			<th>Name</th>
			<th>Options</th>
		</thead>

		
			{% for x in product_list %}
			
			<tr>	
				<td> {{ forloop.counter }}</td>	
				<td><a href= "{{ x.get_absolute_url }}" >
			{{x.product_code}}</a></td>
				<td>{{x.product_name}}</td>
				<td><a href="{% url 'billingapp:update_product' pk=x.pk %}">Edit</a></td>					
			</tr>
			
			{% endfor %}

	</table>

	<br>

	<a href="{% url 'billingapp:entry_product'%}">Click here to Add Products</a>

	<p>
		<ul>
			
			<li><a href ="{% url 'billingapp:list_inventory' %}">Inventory List</a></li>
		</ul>
		
	</p>

{% endblock %}

project_alpha/billingapp/templates/billingapp/vendor_detail.html
{% extends 'billingapp/billingapp_base.html' %}

{% block body_block %}

	<h3>Vendor Detail Page</h3>
	<h1> <b>		{{vendor}}		</b></h1>

	<h5><a href="{%url 'billingapp:update_vendor' pk=vendor.pk %}">Edit</a></h5>

	
<div>
	<h3><u> List of Products Supplied by the Vendor :</u></h3>

	<ul>
		{% for x in productz %}
		<li> {{x.product_code}}</li>
		{% endfor %}
	</ul>
</div>

	<p>
		<a href="{% url 'billingapp:list_vendor'%}">Click here to Go to Vendor List</a>
	</p>

{% endblock %}

project_alpha/billingapp/templates/billingapp/vendor_list.html
{% extends 'billingapp/billingapp_base.html' %}

{% load static %}

{% block body_block %}

<div class="row">
	<div class="col">
		<h2>Vendors</h2>
	</div>
	<div class="col">
		<a href="{% url 'billingapp:entry_vendor' %}" id="add_vendor_btn"><button type="button" class="btn btn-primary">Add New</button></a>
	</div>
</div>

<table class="table table-bordered">
	<thead>
		<th>S.No</th>			
		<th>Name</th>
		<th colspan="2">Options</th>
	</thead>
	<tbody class="two-col-form">
		{% for x in vendor_list %}
		<tr>
			<td>{{forloop.counter}}</td>			
			<td><a href= "{{ x.get_absolute_url }}" >{{x.vendor_name}}</a></td>
			<td><a href="{%url 'billingapp:update_vendor' pk=x.pk %}"><button type="button" class="btn btn-dark">Edit</button></a></td>
			<td><a href="{%url 'billingapp:delete_vendor' pk=x.pk %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
			{# <td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#vendorDeleteModal" data-vendor-id="{{x.vendor_id}}" data-vendor-name="{{x.vendor_name}}">Delete</button></td> #}
		</tr>
		{% endfor %}
	</tbody>
</table>


{% endblock %}